# Alembic Configuration File

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field when generating a new migration
# (does not affect names supplied in revision scripts)
# truncate_slug_len = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# set to 'true' to ignore whitespace-only diffs when
# generating the new migration
# ignore_whitespace = false

# set to true to run `alembic stamp head` automatically
# when revision files
# are generated
# on_version_apply =

# naming convention used when creating foreign keys, check constraints
# and indexes. The default '%(constraint_name)s' matches what most databases
# generate by default when issuing CREATE INDEX or explicit FK constrains that
# don't have an explicit name. Consider using 'ix_%(column_0_name)s' style naming
# to better produce self documenting constraints and expressions.
naming_convention = %(constraint)s

# Logging configuration
# The format string (%%(relativeCreated)d %%(process)d %%(levelname)s %%(name)s %%(message)s)
# is used by the `logging_config` value.
# When non-blank, `logging.config.fileConfig()` is used to configure logging otherwise
# following is used by `logging.basicConfig()` for console output

#logging_config =
#file_logging_format = %%(relativeCreated)d %%(process)d %%(levelname)s %%(name)s %%(message)s

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %H:%M:%S
